### PR TITLE
Create acq directory

### PR DESCRIPTION
**Pull request by pawlowska**
I copied the code from Micro-Manager Multidimensional Acquisition: if
specified directory doesn't exist, the plugin now asks whether to create
it. This is faster and more comfortable than creating it by hand.

### CODE REVIEW

**Comment by dscho** [comment]
Excellent, thank you so much!

**Comment by pawlowska** [comment]
turns out it is possible to do all that (commit and pull request) using only the GUI of the gitbhub software and the website. I didn't have to write a single word in the command line :P

**Comment by dscho** [comment]
Heh... I usually have to compile and test my changes, otherwise I am prone to introduce bugs that force me to wear a brown paper bag over my head out of pure shame...

**Comment by dscho** [comment]
Ah, oops, you mentioned the GitHub software. So yes, you tested locally ;-) I met some of the GitHub for Windows developers recently and had a chance to thank them for their incredibly useful software.

**Comment by dscho** [comment]
... and now the new SPIMAcquisition plugin is uploaded to the update site, with your enhanced acq directory dialog!

**Comment by pawlowska** [comment]
yes, sure, I compiled with eclipse and tested in Micro-Manager by taking a tiny test stack and seeing that it got saved in the newly created directory.

**Pull request merged**
