### PR TITLE
SPIMAcquisition_DAC_FW_control

### PR DESCRIPTION
**Pull request by winfrees**
@dscho.  Johannes, Everything seems to take about a week longer than desired....

Here are the changes I've made to allow control of an Arduino based DAC (6 channel) and Sutter filter wheel.  I added a substantial amount of GUI flow control, DAC vs laser in Device Manager, acquisition table details, and a new DAC manager to adjust the DAC voltages and the filter wheel position during acq table setup.  I used the existing Device idiom and added DAC, Shutter and Filterwheel device types and classes.  The names for the Arduino-DAC channels are hardcoded-yikes-using the default generated by the adapted arduino driver-also included in the pull request.  An adapted arduino firmware is also included for the DAC support.  I can included the CAD files for the DAC shield, but I figured that should be with the microscope description when it is added to the OpenSPIM site.

Things to improve, 

1) set the default fitlerwheel position or query
2) better work around for the DAC channel name lookup(currently hardcoded)-I might be missing something in the MM API.
3) bidirectional capture of the stack to speed things up with multiple channels
4) better DAC control for sequential capture-shuttering not working during motor movements(settled on speed instead of photobleaching concern for now.)  Lase full stack is the default with DAC support.

I don't have a serial laser/coherent to test with the changes I've made- it is possible I've completely decimated that side of the code.  I don't think I have, but I can't promise one-way or the other. 

Let me know what doesn't fit with the projects/your style and I'll adjust and if there are changes I need to make in terms of implementation.

Thanks.

### CODE REVIEW

**Comment by dscho** [comment]
Thank you so much!

I have a couple of ideas to contribute and will do so after a (hopefully) good night's sleep.

**Comment by dscho** [comment]
Okay, so I worked longer than I wanted on this (although not quite a full week)... The main things I fixed:

- `pom.xml` does not need to be adjusted because we are still in the SNAPSHOT phase leading up to version 1.0.0.
- I removed the binary `mmgr_dal_Arduino.dll` because we really need the sources, and they really have to be integrated with Micro-Manager because we finally use regular Micro-Manager instead of our forked version
- I added commit messages (please proof-read them, I do not know what your intention was, so I guessed)
- There are a metric ton of coding style issues (but not as many as the SPIMAcquisition source code has *already*, as I was appalled to learn)

Please note that we really need to try to clean this up to an extent that the source code is easier to maintain after merging your patch than before (or at least as easy as before), because we need to make it easier, not harder, to collaborate on this code (and keeping a consistent coding style goes a long way in that respect).

The current state of my clean up can be seen [here](https://github.com/openspim/SPIMAcquisition/compare/pull-19-dscho) but it is far from done.

**Comment by winfrees** [comment]
Good to hear from you,
I’ll take a look at the commit messages.  
Understand on the mm adapter, I’ll add the source.  
The pom was me being lazy in keeping track of jars on my end, forgot to switch it back to 1.0.0, my bad. 
 If there are any glaring coding style issues I’m inadvertently adding I’d be happy to correct.  I don’t want to add to the insanity! My first pass was more of an attempt at mimicry. I'll look through the code this weekend and correct stylistic issues-try to bring it down to at least an imperial ton...
Thanks for all your effort.   I took your message to heart regarding the effort-and-time comment you recently made on the OpenSPIM list.

**Comment by dscho** [comment]
Oh, now I feel bad! I did not mean to criticize your work! I just want to help make it better is all. Believe me: your first attempt was much better than what I hear sometimes "oh, you know, we made this change and it works here. No, we did not contribute the fix. Oh, do you still want it? Just ask, we will try to dig out the source code. Now, where was that again." You see, you did *so* much better than most who do not bother to think that nobody had to ask *me* to publish my source code, history and all.

And we'll get your improvements included, rest assured.

**Comment by winfrees** [comment]
I didn’t take it as a criticism, it’s like team writing a grant or paper, have to find the "stylistic equilibrium”.  Regardless,  I hoping to contribute to a lot of the projects you’ve worked on, so the sooner I get in the groove the better!

Cheers

**Comment by dscho** [comment]
> Understand on the mm adapter, I’ll add the source.

Do you still plan to do that?

I am in a meeting with @hkmoon and we're discussing how to proceed with this Pull Request...

**Comment by winfrees** [comment]
Yep.  I've been on an grant writing hiatus and have this and a OpenSPIM wiki update in the near future.  I've set aside tomorrow and Friday to SPIMish pursuits.  Is there anything you'd like me to address-of course finish the code reformatting.  

Seth

**Comment by hkmoon** [comment]
Hi @winfrees,

@dscho asked me to handle this pull request with you. I think that would be great to use ```pull-19-dscho ``` branch and we can polish the codes not to break the previous conventions as possible as we can. So, we can communicate/code on that branch as you can also test the experimental codes in your hardware settings by checking out the branch. 

Recently, @dscho and I re-structured java packages in order to improve the scalability for the future maintenance. That would be awesome to apply this package model on your pull request too.

**Comment by winfrees** [comment]
Hi @hkmoon,

Wow.  The restructuring looks great, @dscho and @hkmoon.  Although, I will miss the ProgramaticAcquisitor.  Every time I worked on that class  I went into a refrain- "The Inquisition, let's begin, the inquisition, now we're in...",  long live Mel Brooks.  

It looks like my former approach will still work through the Row class and the StepTable.  If you don't mind I think it might be easiest for me to fork SPIMAcquisition again and migrate my changes to that...  Then the migration to the new-more succinct package structure would already be there.   Then I could put in for a new pull-request allowing for a simpler merge down the road.  

I'll be working on this tomorrow morning.  Let me know if you have any concerns or comments!

Thanks.

**Comment by hkmoon** [comment]
Hi @winfrees,

I like your idea to migrate it. Thank you so much! 

Quite long time ago, @dscho advised me to have each commit has its own story of change set, which will explain the reason of change. I personally would like to follow his advice. If you think this time is a good exercise for commits with messages, that would be much more appreciated! Even we will be able to check your code based on the well defined commits.

Thanks a lot!

**Pull request closed without merging**
