### PR TITLE
Filename prefix

### PR DESCRIPTION
**Pull request by pawlowska**
My proposition of how to make file names more useful. First, a text box for editing the file name prefix (currently "spim_") is added. Second, for the SPIM Ranges tab the number of tiles is established and used for file name. I tested this, but especially the second part should be tested by somebody else as well.

### CODE REVIEW

**Comment by pawlowska** [comment]
ok, I messed up again. The first two commits was just me getting up to date with openspim:master, I don't know why they show here :/

**Comment by dscho** [comment]
@pawlowska I have a little bit of time today and then from Thursday on. Maybe @hkmoon can walk you through a so-called "rebase" to bring your local repository into the state you want it to be in. Otherwise I could walk you through it via https://gitter.im/openspim/SPIMAcquisition either today or on Thursday.

**Comment by pawlowska** [comment]
Thanks for the offer! I already tried the rebase function once, but since  
most of the tutorials I found are Linux-oriented and I'm on Windows, I  
couldn't get it right and gave up. Maybe I'll try again next week and if I  
fail again, then I'll ask for help. Hopefully I can find a way to submit  
my work from this week in a useful form.

**Comment by pawlowska** [comment]
@dscho @hkmoon ok, it looks like I'm unable to restore order by myself, so if one of you could find time to help me via chat, I'd appreciate that.

**Comment by pawlowska** [comment]
I gave up on trying to fix my fork and instead made a clean fork and a clean commit which became pull request #28 which is hopefully identical everywhere where essential. How can I delete this pull request (the #26 )?

**Comment by dscho** [comment]
No need to delete it. I can just close it ;-)

**Pull request closed without merging**
