### PR TITLE
Use the SciJava fork of Java 3D 1.6

### PR DESCRIPTION
**Pull request by ctrueden**
This means we no longer need users to install a Java 3D into their Java runtimes—we can just ship Java 3D with Fiji, avoiding Java-3D-related deployment issues.

Ultimately, we will switch again to the official Java 3D 1.7 (maintained by JogAmp; package prefixes `org.jogamp.java3d` and `org.jogamp.vecmath`). But it is not released yet, so for now we use the SciJava version; see:
- [scijava/java3d-core](https://github.com/scijava/java3d-core)
- [scijava/java3d-utils](https://github.com/scijava/java3d-utils)
- [scijava/vecmath](https://github.com/scijava/vecmath)

Note that this version of Java 3D requires Java 7; hence, SPIMAcquisition now requires Java 7 by extension.

For further details and rationale, see:
- [This (now outdated) forum post](http://forum.imagej.net/t/java-3d-progress-and-next-steps/135)
- [This JogAmp forum thread](forum.jogamp.org/Java-3D-Use-Maven-to-build-and-publish-Maven-artifacts-td4035555.html)

### CODE REVIEW

**Comment by ctrueden** [comment]
@hkmoon Let me know what you think. This upgrades the minimum Java version from 6 to 7, but it will have to happen eventually. We are on the road to Java 8 across the board.

**Comment by hkmoon** [comment]
@ctrueden I will test it and discuss with Pavel's people before merging into the master. Personally, I prefer Java 8 because I have experienced weird GUI problems with Java 7 and MacOSX. I will keep you updated. Thank you!

**Comment by ctrueden** [comment]
> I will test it and discuss with Pavel's people

Great, thanks.

> I have experienced weird GUI problems with Java 7 and MacOSX.

Indeed, Java 7 on OS X has critical performance issues with image painting, which are only fixed in Java 8.

**Comment by ctrueden** [comment]
@hkmoon Any progress on this? The push toward Java 8 continues...

**Comment by ctrueden** [comment]
:+1: Thanks!

**Pull request merged**
