### PR TITLE
Add max property reading

### PR DESCRIPTION
**Pull request by dscho**

### CODE REVIEW

**Comment by dscho** [comment]
Thanks, @pawlowska this is awesome!

**Comment by dscho** [comment]
I gave this a brief look, and the only thing I would *love* to see changed is to remove the code instead of commenting it out. The result will be much cleaner code IMHO.

So here is how I would like you to proceed: use the *interactive rebase* (which really was called `edit-patch-series` before I had to rename it) to edit the history, then force-push:

```sh
git rebase -i HEAD~4
```

then replace the `pick` commands before the PicardStage and the PicardXYStage commits with `edit`, save and quit the editor. It will "replay" the latest commits, letting you "edit" the commits you marked. The way I would suggest to edit them is to open the respective files in a text editor, remove the commented-out code, stage the changes with `git add <file>`, then *amend* (i.e. *rewrite* the commit) with `git commit --amend -s` and finally continuing the rebase with `git rebase --continue`.

After you have edited both commits, the rebase should have finished, and rewritten your history. To see what it did with your revision graph (i.e. the graph of your Git commits), you can call `gitk HEAD...origin/addMaxPropertyReading` (assuming that `origin` is connected to your fork of the `openspim` repository).

Since this rewrites that branch, you will need to *force* the push: it will "lose" commits that are part of the history of your GitHub repository. You can force the push by prefixing the branch name (or `HEAD` as a synonym for your current branch) with a `+`:

```sh
git push origin +HEAD
```

(This assumes -- again -- that you have connected your forked repository as the `origin` remote).

I hope you do not feel overwhelmed by these steps; it is something Git should make easier, but then, Git is just a 10-year old as of last week, so you might forgive Git for not quite growing up yet ;-)

Once those changes are incorporated into the PR, I would be *happy* to merge it!

**Comment by pawlowska** [comment]
ok, to be honest, I understand almost nothing of this instruction, apart from the "remove commented code" part. I made the branch and the commits using the github website, by first making a fork, then making a branch, then editing files. Is there any chance I could do what you are asking from the website not command line?

**Comment by dscho** [comment]
> Is there any chance I could do what you are asking from the website not command line?

Unfortunately not. It's good that you mentioned that you did not test-compile, I will do that tomorrow and if it compiles, merge.

**Comment by pawlowska** [comment]
W dniu 20.04.2015 o 19:08 dscho <notifications@github.com> pisze:

>> Is there any chance I could do what you are asking from the website not  
>> command line?
>
> Unfortunately not. It's good that you mentioned that you did not  
> test-compile, I will do that tomorrow and if it compiles, merge.

I was afraid of that. Yesterday I installed the GitHub software and tried  
to configure it correctly, but you have to admit it's not very ituitive  
for begginers. Hopefully I'll understand it until the next time I have  
something to contrubute.

Regards,
Monika

**Comment by dscho** [comment]
> Hopefully I'll understand it until the next time I have something to contrubute.

Oh, don't worry. I really hope that you continue to contribute! As far as I am concerned, I will try to help you with your contributions as I can.

**Comment by dscho** [comment]
Thanks! I just merged after verifying that it still compiles.

**Pull request merged**
